export const DEPENDENCIES = [
  'user_roles',
  'recommendations',
  'users',
  'taxonomies',
  'categories',
  'measures',
  'recommendation_measures',
  'recommendation_categories',
  'measure_categories',
  'measure_indicators',
  'indicators',
  'sdgtargets',
  'sdgtarget_measures',
];
