export const DEPENDENCIES = [
  'user_roles',
  'users',
  'taxonomies',
  'framework_taxonomies',
  'categories',
  'indicators',
  'measures',
  'measure_categories',
  'measure_indicators',
  'recommendations',
  'recommendation_measures',
  'recommendation_categories',
  'recommendation_indicators',
];
